### ISSUE TITLE
scalac DualIso.scala not runnning

### ISSUE THREAD

**Issue by jaspec** [s1ck/dualiso#2]
hii..
I tried running dual iso algo example using: scalac DualIso.scala
it says:
DualIso.scala:13: error: object util is not a member of package scalation
import scalation.util.time
                 ^
DualIso.scala:22: error: not found: type GraphMatcher
      extends GraphMatcher (g, q)
              ^
DualIso.scala:21: error: not found: type Graph
class DualIso (g: Graph, q: Graph)
                  ^
DualIso.scala:21: error: not found: type Graph
class DualIso (g: Graph, q: Graph)
                            ^
DualIso.scala:22: error: no arguments allowed for nullary constructor Object: ()Object
      extends GraphMatcher (g, q)
                            ^
DualIso.scala:24: error: not found: type DualSim2
    private val duals        = new DualSim2 (g, q)     // object for Dual Simulation algorithm
                                   ^
DualIso.scala:82: error: not found: value CHECK
                if (matches.size % CHECK == 0) println ("dualIso: matches so far = " + matches.size)
                                   ^
DualIso.scala:137: error: not found: value Graph
    val g = Graph.g1
            ^
DualIso.scala:138: error: not found: value Graph
    val q = Graph.q1
            ^
DualIso.scala:146: error: not found: value time
    val psi = time { matcher.bijections () }              // time the matcher
              ^
DualIso.scala:159: error: not found: value Graph
    val g = Graph.g2
            ^
DualIso.scala:160: error: not found: value Graph
    val q = Graph.q2
            ^
DualIso.scala:168: error: not found: value time
    val psi = time { matcher.bijections () }              // time the matcher
              ^
DualIso.scala:187: error: not found: value GraphGen
    val g = GraphGen.genRandomGraph (gSize, nLabels, gAvDegree, false, "g")
            ^
DualIso.scala:188: error: not found: value GraphGen
    val q = GraphGen.genBFSQuery (qSize, qAvDegree, g, false, "q")
            ^
DualIso.scala:191: error: not found: value time
    val psi = time { matcher.bijections () }              // time the matcher
              ^
16 errors found

Can you help me to make it run properly?

**Comment by s1ck** [comment]
Dude, I think you're in the wrong repo. I guess you're referring to: https://github.com/scalation/scalation/blob/master/scalation_modeling/src/main/scala/scalation/graphalytics/mutable/DualIso.scala
